query($titleSlug: String!) {
    question(titleSlug: $titleSlug) {
        questionFrontendId
        titleSlug
        content
        codeSnippets {
            lang
            langSlug
            code
        }
    }
}