type CodeSnippetNode {
    lang: String
    langSlug: String
    code: String
}
type QuestionNode {
    questionFrontendId: String
    titleSlug: String
    codeSnippets: [CodeSnippetNode]
    content: String
}
type QuestionList {
    totalNum: Int
    data: [QuestionNode]
}
input QuestionListFilterInput {
    searchKeywords: String
}

type Query {
    question(titleSlug: String!) : QuestionNode
    questionList(categorySlug:String, limit: Int, skip: Int, filters: QuestionListFilterInput) : QuestionList
}

schema {
    query: Query
}