type CodeSnippetNode {
    lang: String
    langSlug: String
    code: String
}
type QuestionNode {
    questionFrontendId: String
    titleSlug: String
    codeSnippets: [CodeSnippetNode]
    content: String
}
type QuestionList {
    totalNum: Int
    data: [QuestionNode]
}
input QuestionListFilterInput {
    searchKeywords: String
}

type DailyChallenge {
    date: String
    link: String
    question: QuestionNode
}

type DailyCodingChallengeV2 {
    challenges: [DailyChallenge]
}

type Query {
    question(titleSlug: String!) : QuestionNode
    questionList(categorySlug:String, limit: Int, skip: Int, filters: QuestionListFilterInput) : QuestionList
    dailyCodingChallengeV2(year: Int, month: Int) : DailyCodingChallengeV2
}

schema {
    query: Query
}